using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.UI.Windowing;
using Microsoft.UI.Xaml;
using Monbsoft.BrilliantMediator.Extensions;
using Nagare.Application;
using Nagare.Infrastructure;

namespace Nagare.WinApp;

/// <summary>
/// Composition root of the desktop application (ADR-0006). Builds the generic host — configuration,
/// Application and Infrastructure services, BrilliantMediator registry — then opens the main window.
///
/// The entry point (<c>Main</c>) is generated by the SDK: there is no Program.cs.
/// </summary>
public partial class App : Microsoft.UI.Xaml.Application
{
    private readonly IHost _host;

    private Window? _window;
    private bool _shuttingDown;

    public App()
    {
        InitializeComponent();

        _host = BuildHost();

        // Populates the dispatch registry from the handlers registered at compile time by
        // BrilliantMediator.SourceGenerator (ADR-0007). Without it, every dispatch would throw
        // HandlerNotRegisteredException.
        _host.Services.UseBrilliantMediator();
    }

    /// <summary>Service provider of the running host, for the views and their ViewModels.</summary>
    public IServiceProvider Services => _host.Services;

    private static IHost BuildHost()
    {
        // The content root is the folder of the executable, NOT the current directory: launched from
        // Explorer or from Visual Studio they differ, and appsettings.json would then be missed.
        var builder = Host.CreateApplicationBuilder(new HostApplicationBuilderSettings
        {
            ApplicationName = "Nagare",
            ContentRootPath = AppContext.BaseDirectory
        });

        // Leaving Microsoft.NET.Sdk.Web means losing the IMPLICIT loading of appsettings.json and of
        // the User Secrets. Both are therefore declared here, explicitly. Skipping this would let
        // FfmpegOptions.ExecutablePath silently fall back to "ffmpeg" resolved from the PATH — where
        // it is not, on a machine whose ffmpeg lives outside the PATH (plan §7, phase 3).
        //
        // User Secrets are NOT encrypted: they hold local configuration (ffmpeg paths, test key)
        // only. Real channel keys are protected at rest by Data Protection/DPAPI (ADR-0005).
        builder.Configuration
            .AddJsonFile(Path.Combine(AppContext.BaseDirectory, "appsettings.json"), optional: true, reloadOnChange: false)
            .AddUserSecrets<App>(optional: true);

        builder.Services.AddNagareApplication();
        builder.Services.AddNagareInfrastructure(builder.Configuration);

        return builder.Build();
    }

    protected override async void OnLaunched(LaunchActivatedEventArgs args)
    {
        // Starts the hosted services — the StreamSessionCoordinator among them, whose lifecycle owns
        // the kill of the ffmpeg process on shutdown (SPEC §5).
        await _host.StartAsync();

        _window = new MainWindow();
        _window.AppWindow.Closing += OnMainWindowClosing;
        _window.Activate();
    }

    /// <summary>
    /// Stops the host BEFORE letting the window close. The close is cancelled on first pass, the host
    /// is stopped asynchronously, then the window is closed for real.
    ///
    /// Blocking the UI thread on <c>StopAsync</c> instead would deadlock: the coordinator awaits the
    /// completion of its mailbox loop without ConfigureAwait(false), so its continuation is posted
    /// back to this very thread. Cancel-then-close keeps the message loop alive, which is what lets
    /// ffmpeg actually be killed.
    /// </summary>
    private async void OnMainWindowClosing(AppWindow sender, AppWindowClosingEventArgs args)
    {
        if (_shuttingDown)
            return;   // second pass: shutdown is done, let the window go

        args.Cancel = true;   // must be set before the first await
        _shuttingDown = true;

        try
        {
            await _host.StopAsync();
        }
        catch (Exception ex)
        {
            _host.Services.GetRequiredService<ILogger<App>>()
                .LogError(ex, "Error while shutting the host down.");
        }
        finally
        {
            _host.Dispose();
            _window?.Close();
        }
    }
}
