using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.UI.Windowing;
using Microsoft.UI.Xaml;
using Monbsoft.BrilliantMediator.Extensions;
using Nagare.Application;
using Nagare.Infrastructure;
using Nagare.Presentation;
using Nagare.Presentation.Abstractions;
using Nagare.WinApp.Services;

namespace Nagare.WinApp;

/// <summary>
/// Composition root of the desktop application (ADR-0006). Builds the generic host — configuration,
/// Application and Infrastructure services, BrilliantMediator registry — then opens the main window.
///
/// The entry point (<c>Main</c>) is generated by the SDK: there is no Program.cs.
/// </summary>
public partial class App : Microsoft.UI.Xaml.Application
{
    private readonly IHost _host;

    private Window? _window;
    private bool _shuttingDown;

    public App()
    {
        InitializeComponent();

        _host = BuildHost();

        // Populates the dispatch registry from the handlers registered at compile time by
        // BrilliantMediator.SourceGenerator (ADR-0007). Without it, every dispatch would throw
        // HandlerNotRegisteredException.
        _host.Services.UseBrilliantMediator();
    }

    /// <summary>Service provider of the running host, for the views and their ViewModels.</summary>
    public IServiceProvider Services => _host.Services;

    /// <summary>
    /// Typed access to the running application. <c>Application.Current</c> is typed as the base
    /// class, and the pages need <see cref="Services"/> to resolve their ViewModel.
    /// </summary>
    public static new App Current => (App)Microsoft.UI.Xaml.Application.Current;

    private static IHost BuildHost()
    {
        // The content root is the folder of the executable, NOT the current directory: launched from
        // Explorer or from Visual Studio they differ, and appsettings.json would then be missed.
        var builder = Host.CreateApplicationBuilder(new HostApplicationBuilderSettings
        {
            ApplicationName = "Nagare",
            ContentRootPath = AppContext.BaseDirectory
        });

        // Leaving Microsoft.NET.Sdk.Web means losing the IMPLICIT loading of appsettings.json and of
        // the User Secrets. Both are therefore declared here, explicitly. Skipping this would let
        // FfmpegOptions.ExecutablePath silently fall back to "ffmpeg" resolved from the PATH — where
        // it is not, on a machine whose ffmpeg lives outside the PATH (plan §7, phase 3).
        //
        // User Secrets are NOT encrypted: they hold local configuration (ffmpeg paths, test key)
        // only. Real channel keys are protected at rest by Data Protection/DPAPI (ADR-0005).
        builder.Configuration
            .AddJsonFile(Path.Combine(AppContext.BaseDirectory, "appsettings.json"), optional: true, reloadOnChange: false)
            .AddUserSecrets<App>(optional: true);

        builder.Services.AddNagareApplication();
        builder.Services.AddNagareInfrastructure(builder.Configuration);
        builder.Services.AddNagarePresentation();

        // UI-thread-bound services: the WinUI implementations of the two ports the ViewModels need.
        // Both go through MainWindowContext, because the container is built BEFORE the window exists
        // — nothing could capture a DispatcherQueue or an HWND at this point.
        builder.Services.AddSingleton<MainWindowContext>();
        builder.Services.AddSingleton<IUiDispatcher, UiDispatcher>();
        builder.Services.AddSingleton<IVideoFilePicker, FilePickerService>();

        return builder.Build();
    }

    protected override async void OnLaunched(LaunchActivatedEventArgs args)
    {
        // Starts the hosted services — the StreamSessionCoordinator among them, whose lifecycle owns
        // the kill of the ffmpeg process on shutdown (SPEC §5).
        await _host.StartAsync();

        _window = new MainWindow();

        // From here on, UiDispatcher can reach the UI thread and FilePickerService the HWND. Done
        // BEFORE Activate(): the first page loads on activation and resolves its ViewModel at once.
        _host.Services.GetRequiredService<MainWindowContext>().Attach(_window);

        _window.AppWindow.Closing += OnMainWindowClosing;
        _window.Activate();
    }

    /// <summary>
    /// Stops the host BEFORE letting the window close. The close is cancelled on first pass, the host
    /// is stopped asynchronously, then the window is closed for real.
    ///
    /// Blocking the UI thread on <c>StopAsync</c> instead would deadlock: the coordinator awaits the
    /// completion of its mailbox loop without ConfigureAwait(false), so its continuation is posted
    /// back to this very thread. Cancel-then-close keeps the message loop alive, which is what lets
    /// ffmpeg actually be killed.
    ///
    /// <para>The disposal is <b>asynchronous</b>, and that is not cosmetic. <c>ServiceProvider.Dispose()</c>
    /// THROWS on a singleton that implements <see cref="IAsyncDisposable"/> without
    /// <see cref="IDisposable"/> — which is exactly what the StreamSessionCoordinator is. The
    /// exception used to escape from the finally block BEFORE <c>Close()</c> was reached: clicking
    /// the cross stopped the host but never closed the window, and the application hung, alive,
    /// forever. Constaté en lançant réellement l'app.</para>
    /// </summary>
    private async void OnMainWindowClosing(AppWindow sender, AppWindowClosingEventArgs args)
    {
        if (_shuttingDown)
            return;   // second pass: shutdown is done, let the window go

        args.Cancel = true;   // must be set before the first await
        _shuttingDown = true;

        try
        {
            try
            {
                await _host.StopAsync();
            }
            finally
            {
                // The disposal MUST run even if StopAsync threw or timed out (HostOptions.ShutdownTimeout
                // is 30s by default: past it the token is cancelled and the host rethrows). Disposal is
                // what reaches the coordinator's last-resort Kill(entireProcessTree: true). Skipping it
                // would let the window close, the process die — and FFMPEG KEEP BROADCASTING, orphaned.
                // SPEC §5 forbids exactly that.
                await DisposeHostAsync();
            }
        }
        catch (Exception ex)
        {
            _host.Services.GetRequiredService<ILogger<App>>()
                .LogError(ex, "Error while shutting the host down.");
        }
        finally
        {
            // Whatever happened above, the window MUST close: an application that refuses to die is
            // worse than one that dies badly.
            _window?.Close();
        }
    }

    private async ValueTask DisposeHostAsync()
    {
        if (_host is IAsyncDisposable asyncDisposable)
            await asyncDisposable.DisposeAsync();
        else
            _host.Dispose();
    }
}
